<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $lastKode = Product::max('code');
        $lastNumber = $lastKode ? intval(substr($lastKode, 2)) : 0;
        $product = [
            // Makanan Hewan
            [
                'category_id' => 1,
                'name' => 'Royal Canin Kitten',
                'brand' => 'Royal Canin',
                'stock' => '50',
                'price_buy' => '75000',
                'price_sell' => '85000',
                'unit' => 'Pack',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Whiskas Adult Tuna',
                'brand' => 'Whiskas',
                'stock' => '30',
                'price_buy' => '65000',
                'price_sell' => '75000',
                'unit' => 'Pack',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Pedigree Adult Chicken',
                'brand' => 'Pedigree',
                'stock' => '40',
                'price_buy' => '60000',
                'price_sell' => '70000',
                'unit' => 'Pack',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Friskies Ocean Fish',
                'brand' => 'Friskies',
                'stock' => '60',
                'price_buy' => '50000',
                'price_sell' => '60000',
                'unit' => 'Pack',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Aksesoris Hewan
            [
                'category_id' => 2,
                'name' => 'Kalung Anjing Large',
                'brand' => 'PetGear',
                'stock' => '20',
                'price_buy' => '45000',
                'price_sell' => '55000',
                'unit' => 'Pcs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Mainan Kucing Bola',
                'brand' => 'FunPet',
                'stock' => '100',
                'price_buy' => '15000',
                'price_sell' => '20000',
                'unit' => 'Pcs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Kandang Lipat Medium',
                'brand' => 'PetFold',
                'stock' => '10',
                'price_buy' => '150000',
                'price_sell' => '200000',
                'unit' => 'Unit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Perawatan Hewan
            [
                'category_id' => 3,
                'name' => 'Shampoo Anjing Aloe Vera',
                'brand' => 'CleanPet',
                'stock' => '50',
                'price_buy' => '25000',
                'price_sell' => '30000',
                'unit' => 'Botol',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Sisir Grooming Kucing',
                'brand' => 'PetCare',
                'stock' => '30',
                'price_buy' => '30000',
                'price_sell' => '40000',
                'unit' => 'Pcs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Kesehatan Hewan
            [
                'category_id' => 4,
                'name' => 'Vitamin C Cair',
                'brand' => 'VetLine',
                'stock' => '50',
                'price_buy' => '35000',
                'price_sell' => '45000',
                'unit' => 'Botol',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'name' => 'Obat Anti Kutu Kucing',
                'brand' => 'AntiBug',
                'stock' => '20',
                'price_buy' => '50000',
                'price_sell' => '60000',
                'unit' => 'Botol',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Perlengkapan Hewan
            [
                'category_id' => 5,
                'name' => 'Tempat Makan Stainless',
                'brand' => 'PetDish',
                'stock' => '40',
                'price_buy' => '30000',
                'price_sell' => '40000',
                'unit' => 'Pcs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Alas Tidur Kucing',
                'brand' => 'SoftCat',
                'stock' => '25',
                'price_buy' => '70000',
                'price_sell' => '80000',
                'unit' => 'Unit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'SmartHeart Puppy Beef',
                'brand' => 'SmartHeart',
                'stock' => '70',
                'price_buy' => '45000',
                'price_sell' => '55000',
                'unit' => 'Pack',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Me-O Tuna Cat Food',
                'brand' => 'Me-O',
                'stock' => '80',
                'price_buy' => '50000',
                'price_sell' => '60000',
                'unit' => 'Pack',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Dog Cho Chicken',
                'brand' => 'Dog Cho',
                'stock' => '50',
                'price_buy' => '40000',
                'price_sell' => '50000',
                'unit' => 'Pack',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Canary Premium Seeds',
                'brand' => 'BirdCare',
                'stock' => '100',
                'price_buy' => '20000',
                'price_sell' => '30000',
                'unit' => 'Pack',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Aksesoris Hewan
            [
                'category_id' => 2,
                'name' => 'Harness Anjing Large',
                'brand' => 'DogPro',
                'stock' => '25',
                'price_buy' => '70000',
                'price_sell' => '85000',
                'unit' => 'Pcs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Mainan Gantung Burung',
                'brand' => 'BirdFun',
                'stock' => '50',
                'price_buy' => '25000',
                'price_sell' => '35000',
                'unit' => 'Pcs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Kalung Kucing Bell',
                'brand' => 'CatChime',
                'stock' => '60',
                'price_buy' => '10000',
                'price_sell' => '15000',
                'unit' => 'Pcs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Perawatan Hewan
            [
                'category_id' => 3,
                'name' => 'Pasta Gigi Anjing Mint',
                'brand' => 'PetSmile',
                'stock' => '40',
                'price_buy' => '30000',
                'price_sell' => '40000',
                'unit' => 'Tube',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Bedak Anti Kutu',
                'brand' => 'PestFree',
                'stock' => '30',
                'price_buy' => '20000',
                'price_sell' => '30000',
                'unit' => 'Botol',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Kesehatan Hewan
            [
                'category_id' => 4,
                'name' => 'Obat Cacing Kucing',
                'brand' => 'VetHealth',
                'stock' => '35',
                'price_buy' => '45000',
                'price_sell' => '55000',
                'unit' => 'Botol',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'name' => 'Suplemen Kalsium Anjing',
                'brand' => 'BoneCare',
                'stock' => '20',
                'price_buy' => '60000',
                'price_sell' => '75000',
                'unit' => 'Botol',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Perlengkapan Hewan
            [
                'category_id' => 5,
                'name' => 'Kandang Anjing XL',
                'brand' => 'PetSafe',
                'stock' => '10',
                'price_buy' => '300000',
                'price_sell' => '350000',
                'unit' => 'Unit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Dispenser Minum Hewan',
                'brand' => 'AquaPet',
                'stock' => '30',
                'price_buy' => '70000',
                'price_sell' => '85000',
                'unit' => 'Pcs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Pro Plan Adult Chicken',
                'brand' => 'Pro Plan',
                'stock' => '60',
                'price_buy' => '90000',
                'price_sell' => '100000',
                'unit' => 'Pack',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Whiskas Pouch Tuna',
                'brand' => 'Whiskas',
                'stock' => '80',
                'price_buy' => '5000',
                'price_sell' => '8000',
                'unit' => 'Pouch',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Felix As Good As It Looks',
                'brand' => 'Felix',
                'stock' => '50',
                'price_buy' => '15000',
                'price_sell' => '20000',
                'unit' => 'Pouch',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Aksesoris Hewan
            [
                'category_id' => 2,
                'name' => 'Scratching Post Kucing',
                'brand' => 'CatPlay',
                'stock' => '15',
                'price_buy' => '100000',
                'price_sell' => '120000',
                'unit' => 'Unit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Harness Kucing Adjustable',
                'brand' => 'PurrSafe',
                'stock' => '30',
                'price_buy' => '50000',
                'price_sell' => '60000',
                'unit' => 'Pcs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Mainan Anjing Chew Ball',
                'brand' => 'DogFun',
                'stock' => '70',
                'price_buy' => '25000',
                'price_sell' => '30000',
                'unit' => 'Pcs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Perawatan Hewan
            [
                'category_id' => 3,
                'name' => 'Deodorizer Kandang',
                'brand' => 'FreshPet',
                'stock' => '40',
                'price_buy' => '25000',
                'price_sell' => '30000',
                'unit' => 'Spray',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Pewangi Grooming Hewan',
                'brand' => 'ScentCare',
                'stock' => '30',
                'price_buy' => '35000',
                'price_sell' => '45000',
                'unit' => 'Spray',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Cairan Pembersih Telinga',
                'brand' => 'EarCare',
                'stock' => '20',
                'price_buy' => '30000',
                'price_sell' => '40000',
                'unit' => 'Botol',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Kesehatan Hewan
            [
                'category_id' => 4,
                'name' => 'Obat Diare Anjing',
                'brand' => 'GutHealth',
                'stock' => '15',
                'price_buy' => '40000',
                'price_sell' => '50000',
                'unit' => 'Botol',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'name' => 'Vitamin Kucing Hairball',
                'brand' => 'FurCare',
                'stock' => '30',
                'price_buy' => '45000',
                'price_sell' => '55000',
                'unit' => 'Botol',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'name' => 'Probiotic Anjing',
                'brand' => 'PetDigest',
                'stock' => '25',
                'price_buy' => '50000',
                'price_sell' => '60000',
                'unit' => 'Botol',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Perlengkapan Hewan
            [
                'category_id' => 5,
                'name' => 'Botol Minum Portable',
                'brand' => 'HydroPet',
                'stock' => '50',
                'price_buy' => '30000',
                'price_sell' => '40000',
                'unit' => 'Pcs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Matras Anti Air',
                'brand' => 'DryPet',
                'stock' => '30',
                'price_buy' => '80000',
                'price_sell' => '100000',
                'unit' => 'Unit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Kandang Kucing Portable',
                'brand' => 'CarryPet',
                'stock' => '10',
                'price_buy' => '150000',
                'price_sell' => '180000',
                'unit' => 'Unit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        foreach ($product as $items){
            $lastNumber++;
            $product['code'] = 'BR' .str_pad($lastNumber,4,'0',STR_PAD_LEFT);

            Product::create($items);
        }
    }
}
